set nocompatible
set hidden
set relativenumber
set encoding=utf-8
set termencoding=utf-8
set fileencoding=utf-8
set fileencodings=ucs-bom,utf-8,cp936,gb18030
set backspace=indent,eol,start
set nobackup
set nowritebackup
" 加载lua主配置
lua require('init')
