set nocompatible
set hidden
set number
set relativenumber
set numberwidth=4
set encoding=utf-8
set termencoding=utf-8
set fileencoding=utf-8
set fileencodings=ucs-bom,utf-8,cp936,gb18030
set backspace=indent,eol,start
set nobackup
set nowritebackup
set ts=4
set softtabstop=4
set shiftwidth=4
set expandtab
set autoindent
" 加载lua主配置
lua require('init')
